/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as ChooseRoleRouteImport } from './routes/choose-role'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIndexRouteImport } from './routes/user/index'
import { Route as OwnerIndexRouteImport } from './routes/owner/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as UserSupportRouteImport } from './routes/user/support'
import { Route as UserSettingsRouteImport } from './routes/user/settings'
import { Route as UserReportsRouteImport } from './routes/user/reports'
import { Route as UserProfileRouteImport } from './routes/user/profile'
import { Route as UserOnboardingRouteImport } from './routes/user/onboarding'
import { Route as UserMonitoringRouteImport } from './routes/user/monitoring'
import { Route as UserLoginRouteImport } from './routes/user/login'
import { Route as UserLeaveRouteImport } from './routes/user/leave'
import { Route as UserHomeRouteImport } from './routes/user/home'
import { Route as UserDashboardRouteImport } from './routes/user/dashboard'
import { Route as UserBreaksRouteImport } from './routes/user/breaks'
import { Route as UserAlertsRouteImport } from './routes/user/alerts'
import { Route as OwnerUsersRouteImport } from './routes/owner/users'
import { Route as OwnerSubscriptionsRouteImport } from './routes/owner/subscriptions'
import { Route as OwnerSettingsRouteImport } from './routes/owner/settings'
import { Route as OwnerRevenueRouteImport } from './routes/owner/revenue'
import { Route as OwnerReportsRouteImport } from './routes/owner/reports'
import { Route as OwnerLoginRouteImport } from './routes/owner/login'
import { Route as OwnerIssuesRouteImport } from './routes/owner/issues'
import { Route as OwnerIotRouteImport } from './routes/owner/iot'
import { Route as OwnerDashboardRouteImport } from './routes/owner/dashboard'
import { Route as OwnerCreateManagerRouteImport } from './routes/owner/create-manager'
import { Route as OwnerCompaniesRouteImport } from './routes/owner/companies'
import { Route as OwnerCameraRouteImport } from './routes/owner/camera'
import { Route as OwnerAlertsRouteImport } from './routes/owner/alerts'
import { Route as OwnerActivityRouteImport } from './routes/owner/activity'
import { Route as AuthSetPasswordRouteImport } from './routes/auth/set-password'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AdminWorkforceRouteImport } from './routes/admin/workforce'
import { Route as AdminSupportRouteImport } from './routes/admin/support'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminRestRouteImport } from './routes/admin/rest'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminOnboardingRouteImport } from './routes/admin/onboarding'
import { Route as AdminHierarchyRouteImport } from './routes/admin/hierarchy'
import { Route as AdminFatigueDashboardRouteImport } from './routes/admin/fatigue-dashboard'
import { Route as AdminDevicesRouteImport } from './routes/admin/devices'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCreateManagerRouteImport } from './routes/admin/create-manager'
import { Route as AdminCameraRouteImport } from './routes/admin/camera'
import { Route as AdminBillingRouteImport } from './routes/admin/billing'
import { Route as AdminAlertsRouteImport } from './routes/admin/alerts'
import { Route as OwnerCompaniesIndexRouteImport } from './routes/owner/companies.index'
import { Route as OwnerCompanyIdRouteImport } from './routes/owner/company.$id'
import { Route as OwnerCompaniesNewRouteImport } from './routes/owner/companies.new'
import { Route as AdminEmployeeIdRouteImport } from './routes/admin/employee.$id'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const ChooseRoleRoute = ChooseRoleRouteImport.update({
  id: '/choose-role',
  path: '/choose-role',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserRoute,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const UserSupportRoute = UserSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => UserRoute,
} as any)
const UserSettingsRoute = UserSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => UserRoute,
} as any)
const UserReportsRoute = UserReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => UserRoute,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => UserRoute,
} as any)
const UserOnboardingRoute = UserOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => UserRoute,
} as any)
const UserMonitoringRoute = UserMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => UserRoute,
} as any)
const UserLoginRoute = UserLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => UserRoute,
} as any)
const UserLeaveRoute = UserLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => UserRoute,
} as any)
const UserHomeRoute = UserHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => UserRoute,
} as any)
const UserDashboardRoute = UserDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => UserRoute,
} as any)
const UserBreaksRoute = UserBreaksRouteImport.update({
  id: '/breaks',
  path: '/breaks',
  getParentRoute: () => UserRoute,
} as any)
const UserAlertsRoute = UserAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => UserRoute,
} as any)
const OwnerUsersRoute = OwnerUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerSubscriptionsRoute = OwnerSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerSettingsRoute = OwnerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerRevenueRoute = OwnerRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerReportsRoute = OwnerReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerLoginRoute = OwnerLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerIssuesRoute = OwnerIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerIotRoute = OwnerIotRouteImport.update({
  id: '/iot',
  path: '/iot',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerDashboardRoute = OwnerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerCreateManagerRoute = OwnerCreateManagerRouteImport.update({
  id: '/create-manager',
  path: '/create-manager',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerCompaniesRoute = OwnerCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerCameraRoute = OwnerCameraRouteImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerAlertsRoute = OwnerAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerActivityRoute = OwnerActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => OwnerRoute,
} as any)
const AuthSetPasswordRoute = AuthSetPasswordRouteImport.update({
  id: '/auth/set-password',
  path: '/auth/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorkforceRoute = AdminWorkforceRouteImport.update({
  id: '/workforce',
  path: '/workforce',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRestRoute = AdminRestRouteImport.update({
  id: '/rest',
  path: '/rest',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOnboardingRoute = AdminOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHierarchyRoute = AdminHierarchyRouteImport.update({
  id: '/hierarchy',
  path: '/hierarchy',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFatigueDashboardRoute = AdminFatigueDashboardRouteImport.update({
  id: '/fatigue-dashboard',
  path: '/fatigue-dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDevicesRoute = AdminDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCreateManagerRoute = AdminCreateManagerRouteImport.update({
  id: '/create-manager',
  path: '/create-manager',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCameraRoute = AdminCameraRouteImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlertsRoute = AdminAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AdminRoute,
} as any)
const OwnerCompaniesIndexRoute = OwnerCompaniesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerCompaniesRoute,
} as any)
const OwnerCompanyIdRoute = OwnerCompanyIdRouteImport.update({
  id: '/company/$id',
  path: '/company/$id',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerCompaniesNewRoute = OwnerCompaniesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => OwnerCompaniesRoute,
} as any)
const AdminEmployeeIdRoute = AdminEmployeeIdRouteImport.update({
  id: '/employee/$id',
  path: '/employee/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/choose-role': typeof ChooseRoleRoute
  '/owner': typeof OwnerRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/camera': typeof AdminCameraRoute
  '/admin/create-manager': typeof AdminCreateManagerRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/devices': typeof AdminDevicesRoute
  '/admin/fatigue-dashboard': typeof AdminFatigueDashboardRoute
  '/admin/hierarchy': typeof AdminHierarchyRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/rest': typeof AdminRestRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/workforce': typeof AdminWorkforceRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/owner/activity': typeof OwnerActivityRoute
  '/owner/alerts': typeof OwnerAlertsRoute
  '/owner/camera': typeof OwnerCameraRoute
  '/owner/companies': typeof OwnerCompaniesRouteWithChildren
  '/owner/create-manager': typeof OwnerCreateManagerRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/iot': typeof OwnerIotRoute
  '/owner/issues': typeof OwnerIssuesRoute
  '/owner/login': typeof OwnerLoginRoute
  '/owner/reports': typeof OwnerReportsRoute
  '/owner/revenue': typeof OwnerRevenueRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/owner/subscriptions': typeof OwnerSubscriptionsRoute
  '/owner/users': typeof OwnerUsersRoute
  '/user/alerts': typeof UserAlertsRoute
  '/user/breaks': typeof UserBreaksRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/home': typeof UserHomeRoute
  '/user/leave': typeof UserLeaveRoute
  '/user/login': typeof UserLoginRoute
  '/user/monitoring': typeof UserMonitoringRoute
  '/user/onboarding': typeof UserOnboardingRoute
  '/user/profile': typeof UserProfileRoute
  '/user/reports': typeof UserReportsRoute
  '/user/settings': typeof UserSettingsRoute
  '/user/support': typeof UserSupportRoute
  '/admin/': typeof AdminIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/user/': typeof UserIndexRoute
  '/admin/employee/$id': typeof AdminEmployeeIdRoute
  '/owner/companies/new': typeof OwnerCompaniesNewRoute
  '/owner/company/$id': typeof OwnerCompanyIdRoute
  '/owner/companies/': typeof OwnerCompaniesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/choose-role': typeof ChooseRoleRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/camera': typeof AdminCameraRoute
  '/admin/create-manager': typeof AdminCreateManagerRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/devices': typeof AdminDevicesRoute
  '/admin/fatigue-dashboard': typeof AdminFatigueDashboardRoute
  '/admin/hierarchy': typeof AdminHierarchyRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/rest': typeof AdminRestRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/workforce': typeof AdminWorkforceRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/owner/activity': typeof OwnerActivityRoute
  '/owner/alerts': typeof OwnerAlertsRoute
  '/owner/camera': typeof OwnerCameraRoute
  '/owner/create-manager': typeof OwnerCreateManagerRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/iot': typeof OwnerIotRoute
  '/owner/issues': typeof OwnerIssuesRoute
  '/owner/login': typeof OwnerLoginRoute
  '/owner/reports': typeof OwnerReportsRoute
  '/owner/revenue': typeof OwnerRevenueRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/owner/subscriptions': typeof OwnerSubscriptionsRoute
  '/owner/users': typeof OwnerUsersRoute
  '/user/alerts': typeof UserAlertsRoute
  '/user/breaks': typeof UserBreaksRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/home': typeof UserHomeRoute
  '/user/leave': typeof UserLeaveRoute
  '/user/login': typeof UserLoginRoute
  '/user/monitoring': typeof UserMonitoringRoute
  '/user/onboarding': typeof UserOnboardingRoute
  '/user/profile': typeof UserProfileRoute
  '/user/reports': typeof UserReportsRoute
  '/user/settings': typeof UserSettingsRoute
  '/user/support': typeof UserSupportRoute
  '/admin': typeof AdminIndexRoute
  '/owner': typeof OwnerIndexRoute
  '/user': typeof UserIndexRoute
  '/admin/employee/$id': typeof AdminEmployeeIdRoute
  '/owner/companies/new': typeof OwnerCompaniesNewRoute
  '/owner/company/$id': typeof OwnerCompanyIdRoute
  '/owner/companies': typeof OwnerCompaniesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/choose-role': typeof ChooseRoleRoute
  '/owner': typeof OwnerRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/camera': typeof AdminCameraRoute
  '/admin/create-manager': typeof AdminCreateManagerRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/devices': typeof AdminDevicesRoute
  '/admin/fatigue-dashboard': typeof AdminFatigueDashboardRoute
  '/admin/hierarchy': typeof AdminHierarchyRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/rest': typeof AdminRestRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/workforce': typeof AdminWorkforceRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/owner/activity': typeof OwnerActivityRoute
  '/owner/alerts': typeof OwnerAlertsRoute
  '/owner/camera': typeof OwnerCameraRoute
  '/owner/companies': typeof OwnerCompaniesRouteWithChildren
  '/owner/create-manager': typeof OwnerCreateManagerRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/iot': typeof OwnerIotRoute
  '/owner/issues': typeof OwnerIssuesRoute
  '/owner/login': typeof OwnerLoginRoute
  '/owner/reports': typeof OwnerReportsRoute
  '/owner/revenue': typeof OwnerRevenueRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/owner/subscriptions': typeof OwnerSubscriptionsRoute
  '/owner/users': typeof OwnerUsersRoute
  '/user/alerts': typeof UserAlertsRoute
  '/user/breaks': typeof UserBreaksRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/home': typeof UserHomeRoute
  '/user/leave': typeof UserLeaveRoute
  '/user/login': typeof UserLoginRoute
  '/user/monitoring': typeof UserMonitoringRoute
  '/user/onboarding': typeof UserOnboardingRoute
  '/user/profile': typeof UserProfileRoute
  '/user/reports': typeof UserReportsRoute
  '/user/settings': typeof UserSettingsRoute
  '/user/support': typeof UserSupportRoute
  '/admin/': typeof AdminIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/user/': typeof UserIndexRoute
  '/admin/employee/$id': typeof AdminEmployeeIdRoute
  '/owner/companies/new': typeof OwnerCompaniesNewRoute
  '/owner/company/$id': typeof OwnerCompanyIdRoute
  '/owner/companies/': typeof OwnerCompaniesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/choose-role'
    | '/owner'
    | '/user'
    | '/admin/alerts'
    | '/admin/billing'
    | '/admin/camera'
    | '/admin/create-manager'
    | '/admin/dashboard'
    | '/admin/devices'
    | '/admin/fatigue-dashboard'
    | '/admin/hierarchy'
    | '/admin/onboarding'
    | '/admin/reports'
    | '/admin/rest'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/workforce'
    | '/auth/callback'
    | '/auth/set-password'
    | '/owner/activity'
    | '/owner/alerts'
    | '/owner/camera'
    | '/owner/companies'
    | '/owner/create-manager'
    | '/owner/dashboard'
    | '/owner/iot'
    | '/owner/issues'
    | '/owner/login'
    | '/owner/reports'
    | '/owner/revenue'
    | '/owner/settings'
    | '/owner/subscriptions'
    | '/owner/users'
    | '/user/alerts'
    | '/user/breaks'
    | '/user/dashboard'
    | '/user/home'
    | '/user/leave'
    | '/user/login'
    | '/user/monitoring'
    | '/user/onboarding'
    | '/user/profile'
    | '/user/reports'
    | '/user/settings'
    | '/user/support'
    | '/admin/'
    | '/owner/'
    | '/user/'
    | '/admin/employee/$id'
    | '/owner/companies/new'
    | '/owner/company/$id'
    | '/owner/companies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/choose-role'
    | '/admin/alerts'
    | '/admin/billing'
    | '/admin/camera'
    | '/admin/create-manager'
    | '/admin/dashboard'
    | '/admin/devices'
    | '/admin/fatigue-dashboard'
    | '/admin/hierarchy'
    | '/admin/onboarding'
    | '/admin/reports'
    | '/admin/rest'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/workforce'
    | '/auth/callback'
    | '/auth/set-password'
    | '/owner/activity'
    | '/owner/alerts'
    | '/owner/camera'
    | '/owner/create-manager'
    | '/owner/dashboard'
    | '/owner/iot'
    | '/owner/issues'
    | '/owner/login'
    | '/owner/reports'
    | '/owner/revenue'
    | '/owner/settings'
    | '/owner/subscriptions'
    | '/owner/users'
    | '/user/alerts'
    | '/user/breaks'
    | '/user/dashboard'
    | '/user/home'
    | '/user/leave'
    | '/user/login'
    | '/user/monitoring'
    | '/user/onboarding'
    | '/user/profile'
    | '/user/reports'
    | '/user/settings'
    | '/user/support'
    | '/admin'
    | '/owner'
    | '/user'
    | '/admin/employee/$id'
    | '/owner/companies/new'
    | '/owner/company/$id'
    | '/owner/companies'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/choose-role'
    | '/owner'
    | '/user'
    | '/admin/alerts'
    | '/admin/billing'
    | '/admin/camera'
    | '/admin/create-manager'
    | '/admin/dashboard'
    | '/admin/devices'
    | '/admin/fatigue-dashboard'
    | '/admin/hierarchy'
    | '/admin/onboarding'
    | '/admin/reports'
    | '/admin/rest'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/workforce'
    | '/auth/callback'
    | '/auth/set-password'
    | '/owner/activity'
    | '/owner/alerts'
    | '/owner/camera'
    | '/owner/companies'
    | '/owner/create-manager'
    | '/owner/dashboard'
    | '/owner/iot'
    | '/owner/issues'
    | '/owner/login'
    | '/owner/reports'
    | '/owner/revenue'
    | '/owner/settings'
    | '/owner/subscriptions'
    | '/owner/users'
    | '/user/alerts'
    | '/user/breaks'
    | '/user/dashboard'
    | '/user/home'
    | '/user/leave'
    | '/user/login'
    | '/user/monitoring'
    | '/user/onboarding'
    | '/user/profile'
    | '/user/reports'
    | '/user/settings'
    | '/user/support'
    | '/admin/'
    | '/owner/'
    | '/user/'
    | '/admin/employee/$id'
    | '/owner/companies/new'
    | '/owner/company/$id'
    | '/owner/companies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ChooseRoleRoute: typeof ChooseRoleRoute
  OwnerRoute: typeof OwnerRouteWithChildren
  UserRoute: typeof UserRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthSetPasswordRoute: typeof AuthSetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/choose-role': {
      id: '/choose-role'
      path: '/choose-role'
      fullPath: '/choose-role'
      preLoaderRoute: typeof ChooseRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/owner/': {
      id: '/owner/'
      path: '/'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/user/support': {
      id: '/user/support'
      path: '/support'
      fullPath: '/user/support'
      preLoaderRoute: typeof UserSupportRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/settings': {
      id: '/user/settings'
      path: '/settings'
      fullPath: '/user/settings'
      preLoaderRoute: typeof UserSettingsRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/reports': {
      id: '/user/reports'
      path: '/reports'
      fullPath: '/user/reports'
      preLoaderRoute: typeof UserReportsRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/profile': {
      id: '/user/profile'
      path: '/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/onboarding': {
      id: '/user/onboarding'
      path: '/onboarding'
      fullPath: '/user/onboarding'
      preLoaderRoute: typeof UserOnboardingRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/monitoring': {
      id: '/user/monitoring'
      path: '/monitoring'
      fullPath: '/user/monitoring'
      preLoaderRoute: typeof UserMonitoringRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/login': {
      id: '/user/login'
      path: '/login'
      fullPath: '/user/login'
      preLoaderRoute: typeof UserLoginRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/leave': {
      id: '/user/leave'
      path: '/leave'
      fullPath: '/user/leave'
      preLoaderRoute: typeof UserLeaveRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/home': {
      id: '/user/home'
      path: '/home'
      fullPath: '/user/home'
      preLoaderRoute: typeof UserHomeRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/dashboard': {
      id: '/user/dashboard'
      path: '/dashboard'
      fullPath: '/user/dashboard'
      preLoaderRoute: typeof UserDashboardRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/breaks': {
      id: '/user/breaks'
      path: '/breaks'
      fullPath: '/user/breaks'
      preLoaderRoute: typeof UserBreaksRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/alerts': {
      id: '/user/alerts'
      path: '/alerts'
      fullPath: '/user/alerts'
      preLoaderRoute: typeof UserAlertsRouteImport
      parentRoute: typeof UserRoute
    }
    '/owner/users': {
      id: '/owner/users'
      path: '/users'
      fullPath: '/owner/users'
      preLoaderRoute: typeof OwnerUsersRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/subscriptions': {
      id: '/owner/subscriptions'
      path: '/subscriptions'
      fullPath: '/owner/subscriptions'
      preLoaderRoute: typeof OwnerSubscriptionsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/settings': {
      id: '/owner/settings'
      path: '/settings'
      fullPath: '/owner/settings'
      preLoaderRoute: typeof OwnerSettingsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/revenue': {
      id: '/owner/revenue'
      path: '/revenue'
      fullPath: '/owner/revenue'
      preLoaderRoute: typeof OwnerRevenueRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/reports': {
      id: '/owner/reports'
      path: '/reports'
      fullPath: '/owner/reports'
      preLoaderRoute: typeof OwnerReportsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/login': {
      id: '/owner/login'
      path: '/login'
      fullPath: '/owner/login'
      preLoaderRoute: typeof OwnerLoginRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/issues': {
      id: '/owner/issues'
      path: '/issues'
      fullPath: '/owner/issues'
      preLoaderRoute: typeof OwnerIssuesRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/iot': {
      id: '/owner/iot'
      path: '/iot'
      fullPath: '/owner/iot'
      preLoaderRoute: typeof OwnerIotRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/dashboard': {
      id: '/owner/dashboard'
      path: '/dashboard'
      fullPath: '/owner/dashboard'
      preLoaderRoute: typeof OwnerDashboardRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/create-manager': {
      id: '/owner/create-manager'
      path: '/create-manager'
      fullPath: '/owner/create-manager'
      preLoaderRoute: typeof OwnerCreateManagerRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/companies': {
      id: '/owner/companies'
      path: '/companies'
      fullPath: '/owner/companies'
      preLoaderRoute: typeof OwnerCompaniesRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/camera': {
      id: '/owner/camera'
      path: '/camera'
      fullPath: '/owner/camera'
      preLoaderRoute: typeof OwnerCameraRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/alerts': {
      id: '/owner/alerts'
      path: '/alerts'
      fullPath: '/owner/alerts'
      preLoaderRoute: typeof OwnerAlertsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/activity': {
      id: '/owner/activity'
      path: '/activity'
      fullPath: '/owner/activity'
      preLoaderRoute: typeof OwnerActivityRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/auth/set-password': {
      id: '/auth/set-password'
      path: '/auth/set-password'
      fullPath: '/auth/set-password'
      preLoaderRoute: typeof AuthSetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/workforce': {
      id: '/admin/workforce'
      path: '/workforce'
      fullPath: '/admin/workforce'
      preLoaderRoute: typeof AdminWorkforceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rest': {
      id: '/admin/rest'
      path: '/rest'
      fullPath: '/admin/rest'
      preLoaderRoute: typeof AdminRestRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/onboarding': {
      id: '/admin/onboarding'
      path: '/onboarding'
      fullPath: '/admin/onboarding'
      preLoaderRoute: typeof AdminOnboardingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hierarchy': {
      id: '/admin/hierarchy'
      path: '/hierarchy'
      fullPath: '/admin/hierarchy'
      preLoaderRoute: typeof AdminHierarchyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fatigue-dashboard': {
      id: '/admin/fatigue-dashboard'
      path: '/fatigue-dashboard'
      fullPath: '/admin/fatigue-dashboard'
      preLoaderRoute: typeof AdminFatigueDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/devices': {
      id: '/admin/devices'
      path: '/devices'
      fullPath: '/admin/devices'
      preLoaderRoute: typeof AdminDevicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/create-manager': {
      id: '/admin/create-manager'
      path: '/create-manager'
      fullPath: '/admin/create-manager'
      preLoaderRoute: typeof AdminCreateManagerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/camera': {
      id: '/admin/camera'
      path: '/camera'
      fullPath: '/admin/camera'
      preLoaderRoute: typeof AdminCameraRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alerts': {
      id: '/admin/alerts'
      path: '/alerts'
      fullPath: '/admin/alerts'
      preLoaderRoute: typeof AdminAlertsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/owner/companies/': {
      id: '/owner/companies/'
      path: '/'
      fullPath: '/owner/companies/'
      preLoaderRoute: typeof OwnerCompaniesIndexRouteImport
      parentRoute: typeof OwnerCompaniesRoute
    }
    '/owner/company/$id': {
      id: '/owner/company/$id'
      path: '/company/$id'
      fullPath: '/owner/company/$id'
      preLoaderRoute: typeof OwnerCompanyIdRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/companies/new': {
      id: '/owner/companies/new'
      path: '/new'
      fullPath: '/owner/companies/new'
      preLoaderRoute: typeof OwnerCompaniesNewRouteImport
      parentRoute: typeof OwnerCompaniesRoute
    }
    '/admin/employee/$id': {
      id: '/admin/employee/$id'
      path: '/employee/$id'
      fullPath: '/admin/employee/$id'
      preLoaderRoute: typeof AdminEmployeeIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAlertsRoute: typeof AdminAlertsRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminCameraRoute: typeof AdminCameraRoute
  AdminCreateManagerRoute: typeof AdminCreateManagerRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDevicesRoute: typeof AdminDevicesRoute
  AdminFatigueDashboardRoute: typeof AdminFatigueDashboardRoute
  AdminHierarchyRoute: typeof AdminHierarchyRoute
  AdminOnboardingRoute: typeof AdminOnboardingRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRestRoute: typeof AdminRestRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminWorkforceRoute: typeof AdminWorkforceRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEmployeeIdRoute: typeof AdminEmployeeIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAlertsRoute: AdminAlertsRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminCameraRoute: AdminCameraRoute,
  AdminCreateManagerRoute: AdminCreateManagerRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDevicesRoute: AdminDevicesRoute,
  AdminFatigueDashboardRoute: AdminFatigueDashboardRoute,
  AdminHierarchyRoute: AdminHierarchyRoute,
  AdminOnboardingRoute: AdminOnboardingRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRestRoute: AdminRestRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminWorkforceRoute: AdminWorkforceRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEmployeeIdRoute: AdminEmployeeIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface OwnerCompaniesRouteChildren {
  OwnerCompaniesNewRoute: typeof OwnerCompaniesNewRoute
  OwnerCompaniesIndexRoute: typeof OwnerCompaniesIndexRoute
}

const OwnerCompaniesRouteChildren: OwnerCompaniesRouteChildren = {
  OwnerCompaniesNewRoute: OwnerCompaniesNewRoute,
  OwnerCompaniesIndexRoute: OwnerCompaniesIndexRoute,
}

const OwnerCompaniesRouteWithChildren = OwnerCompaniesRoute._addFileChildren(
  OwnerCompaniesRouteChildren,
)

interface OwnerRouteChildren {
  OwnerActivityRoute: typeof OwnerActivityRoute
  OwnerAlertsRoute: typeof OwnerAlertsRoute
  OwnerCameraRoute: typeof OwnerCameraRoute
  OwnerCompaniesRoute: typeof OwnerCompaniesRouteWithChildren
  OwnerCreateManagerRoute: typeof OwnerCreateManagerRoute
  OwnerDashboardRoute: typeof OwnerDashboardRoute
  OwnerIotRoute: typeof OwnerIotRoute
  OwnerIssuesRoute: typeof OwnerIssuesRoute
  OwnerLoginRoute: typeof OwnerLoginRoute
  OwnerReportsRoute: typeof OwnerReportsRoute
  OwnerRevenueRoute: typeof OwnerRevenueRoute
  OwnerSettingsRoute: typeof OwnerSettingsRoute
  OwnerSubscriptionsRoute: typeof OwnerSubscriptionsRoute
  OwnerUsersRoute: typeof OwnerUsersRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
  OwnerCompanyIdRoute: typeof OwnerCompanyIdRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerActivityRoute: OwnerActivityRoute,
  OwnerAlertsRoute: OwnerAlertsRoute,
  OwnerCameraRoute: OwnerCameraRoute,
  OwnerCompaniesRoute: OwnerCompaniesRouteWithChildren,
  OwnerCreateManagerRoute: OwnerCreateManagerRoute,
  OwnerDashboardRoute: OwnerDashboardRoute,
  OwnerIotRoute: OwnerIotRoute,
  OwnerIssuesRoute: OwnerIssuesRoute,
  OwnerLoginRoute: OwnerLoginRoute,
  OwnerReportsRoute: OwnerReportsRoute,
  OwnerRevenueRoute: OwnerRevenueRoute,
  OwnerSettingsRoute: OwnerSettingsRoute,
  OwnerSubscriptionsRoute: OwnerSubscriptionsRoute,
  OwnerUsersRoute: OwnerUsersRoute,
  OwnerIndexRoute: OwnerIndexRoute,
  OwnerCompanyIdRoute: OwnerCompanyIdRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

interface UserRouteChildren {
  UserAlertsRoute: typeof UserAlertsRoute
  UserBreaksRoute: typeof UserBreaksRoute
  UserDashboardRoute: typeof UserDashboardRoute
  UserHomeRoute: typeof UserHomeRoute
  UserLeaveRoute: typeof UserLeaveRoute
  UserLoginRoute: typeof UserLoginRoute
  UserMonitoringRoute: typeof UserMonitoringRoute
  UserOnboardingRoute: typeof UserOnboardingRoute
  UserProfileRoute: typeof UserProfileRoute
  UserReportsRoute: typeof UserReportsRoute
  UserSettingsRoute: typeof UserSettingsRoute
  UserSupportRoute: typeof UserSupportRoute
  UserIndexRoute: typeof UserIndexRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserAlertsRoute: UserAlertsRoute,
  UserBreaksRoute: UserBreaksRoute,
  UserDashboardRoute: UserDashboardRoute,
  UserHomeRoute: UserHomeRoute,
  UserLeaveRoute: UserLeaveRoute,
  UserLoginRoute: UserLoginRoute,
  UserMonitoringRoute: UserMonitoringRoute,
  UserOnboardingRoute: UserOnboardingRoute,
  UserProfileRoute: UserProfileRoute,
  UserReportsRoute: UserReportsRoute,
  UserSettingsRoute: UserSettingsRoute,
  UserSupportRoute: UserSupportRoute,
  UserIndexRoute: UserIndexRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ChooseRoleRoute: ChooseRoleRoute,
  OwnerRoute: OwnerRouteWithChildren,
  UserRoute: UserRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthSetPasswordRoute: AuthSetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
