-- ============================================================
-- Seed: Default SentinelAI Owner Account
-- REMOVED — seed data has been cleared.
-- The owner account should be created through the application
-- or via the Supabase dashboard using a secure password.
-- ============================================================
